name: flutter_by_example
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0
  angular_router: ^2.0.0-alpha+22
  angular_bloc: ^0.9.0
  sass_builder: ^2.0.0
  html_unescape: ^1.0.0
  markdown: ^2.0.0
  path: ^1.4.1
  rxdart: ^0.22.0
  meta: any
  bloc: ^0.14.1
  json_serializable: ^3.0.0
  json_annotation: ^2.4.0
  equatable: ^0.2.6
  http: ^0.12.0
  yaml: ^2.0.0

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.6.0
  build_test: ^0.10.8
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  test: ^1.6.0
